controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

# Register api
register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [ 'POST' ]

